apiVersion: apps/v1
kind: Deployment
metadata:
  name:  backend-deployment
  labels:
    app: backend-ms 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-ms
  template:
    metadata:
      labels:
        name:  backend-ms
    spec:
      containers:
      - name:  bloqueo
        image:  1026281452/testhelm:v1
        ports:
        - containerPort: 8080