name: CI
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Build compile project
        run: cd tutotial-helm; mvn clean install

      - name: get leader git username
        id: get_leader_username
        run: |
          cd java_app
          echo "leader_username=$(git log -n 1 --pretty=format:%an)" >> "$GITHUB_OUTPUT"

      - name: get leader git email
        id: get_leader_email
        run: |
          cd java_app
          echo "leader_email=$(git log -n 1 --pretty=format:%ae)" >> "$GITHUB_OUTPUT"

      - name: Set local git creddentials
        run: |
          git config --global user.email "${{ steps.get_leader_email.outputs.leader_email }}"
          git config --global user.name "${{ steps.get_leader_username.outputs.leader_username }}"

      - name: 'Checkout Repo'
        uses: actions/checkout@v4 
        with:
          path: java_app
          fetch-depth: '0'

      - name: get latest tags
        id: get_tag
        run: |
          cd java_app
          git fetch --tags
          latest_tag=$(git describe --tags --abbrev=0 main || echo "v0.0.0")
          echo "current_tag=$latest_tag" >> "$GITHUB_OUTPUT"

      - name: increment version
        id: increment_version
        run: |
          cd java_app
          last_tag="${{steps.get_tag.outputs.current_tag}}"
          while true; do
            if [[ $last_tag == *v* ]]; then
                major=$(echo $last_tag | cut -c2- | cut -d '.' -f1)
            else
                major=$(echo $last_tag | cut -d '.' -f1)
            fi
            minor=$(echo $last_tag | cut -d '.' -f2)
            patch=$(echo $last_tag | cut -d '.' -f3)

            patch=$((patch +1))
            last_tag="$major.$minor.$patch"
            echo "new_version_tag=$last_tag" >> "$GITHUB_OUTPUT"
            break
          done

      - name: created_tag
        run: |
          git tag v${{steps.increment_version.outputs.new_version_tag}}


      - name: Build the docker image
        uses: docker/build-push-action@v4
        with:
          context: ./tutotial-helm
          dockerfile: Dockerfile 
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/testhelm:v${{steps.increment_version.outputs.new_version_tag}}

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: push docker
        uses: docker/build-push-action@v4
        with:
          context: ./tutotial-helm
          dockerfile: Dockerfile 
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/testhelm:v${{steps.increment_version.outputs.new_version_tag}}
      
      - name: Push generated tag
        run: |
          cd java_app
          git push --tags
