name: CI
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Build compile project
        run: cd tutotial-helm; mvn clean install

      - name: Build the docker image
        uses: docker/build-push-action@v4
        with:
          context: ./tutotial-helm
          dockerfile: Dockerfile 
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/testhelm:latest

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: push docker
        uses: docker/build-push-action@v4
        with:
          context: ./tutotial-helm
          dockerfile: Dockerfile 
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/testhelm:latest
