name: CI
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Build compile project
        run: cd tutotial-helm; mvn clean install

      - name: Build the docker image
        uses: docker/build-push-action@v4
        with:
          context: ./tutotial-helm
          dockerfile: Dockerfile 
          push: false
